<a href="https://colab.research.google.com/github/Dhamu785/AI-scratch/blob/main/TensorFlow/01_TF_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to Tensors**

In [ ]:
# import tensorflow
import tensorflow as tf
print(tf.__version__)

2.13.0


## **Creating tensors with `tf.constant`**

### **Scalar values**

In [ ]:
# Create tensors
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
print(scalar)
print(f"Dimension: {scalar}")

tf.Tensor(7, shape=(), dtype=int32)
Dimension: 7


### **Vectors**
- Dimensionality is calculated based on the no. of square brackets
- Vectors are 2D

In [ ]:
# Single vector value

scalar1 = tf.constant([7,45,77])
scalar1

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 7, 45, 77], dtype=int32)>

In [ ]:
print(f"Shape: {scalar1.shape}")
print(f"Dimension: {scalar1.ndim}")

Shape: (3,)
Dimension: 1


In [ ]:
# Two dim vector value

vec1 = tf.constant([[10,7,8],[7,10,9],[7,10,9]])
vec1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[10,  7,  8],
       [ 7, 10,  9],
       [ 7, 10,  9]], dtype=int32)>

In [ ]:
print(f"Shape: {vec1.shape}")
print(f"Dimension: {vec1.ndim}")

Shape: (3, 3)
Dimension: 2


In [ ]:
# Vector value with dtype

vec2 = tf.constant([[1,2,3],[4,5,6],[1,3,5]], dtype=tf.float16)
vec2

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [1., 3., 5.]], dtype=float16)>

In [ ]:
print(f"Dimension: {vec2.ndim}")

Dimension: 2


### **Tensors**

In [ ]:
tensor1 = tf.constant([[[1,2,3],[4,5,6]]])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]]], dtype=int32)>

In [ ]:
print(tensor1)
print(f"Dimensions: {tensor1.ndim}")

tf.Tensor(
[[[1 2 3]
  [4 5 6]]], shape=(1, 2, 3), dtype=int32)
Dimensions: 3


## **Creating tensors with `tf.variable`**

In [ ]:
## tf.constant is not a changable tensor
## tf.variable is a changable tensor

changable_tensor = tf.Variable([2,3,5])
unchangable_tensor = tf.constant([2,3,5])

print(changable_tensor, unchangable_tensor, end='\n', sep='\n')
print()

print(f"changable_tensor = {changable_tensor[0]}")
print(f"unchangable_tensor = {unchangable_tensor[1]}")


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([2, 3, 5], dtype=int32)>
tf.Tensor([2 3 5], shape=(3,), dtype=int32)

changable_tensor = 2
unchangable_tensor = 3


In [ ]:
#Try to modify the values in tensor

changable_tensor[0].assign(7)
print(changable_tensor)
changable_tensor

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([7, 3, 5], dtype=int32)>


<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([7, 3, 5], dtype=int32)>

## **Create random tensors**

In [ ]:
# Random values with uniform distributions

random1 = tf.random.uniform(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.01204789, 0.13359654],
       [0.3902341 , 0.18709636],
       [0.8433286 , 0.4977907 ]], dtype=float32)>

In [ ]:
# Random values with normal distribution

rdm2 = tf.random.normal(shape = (3,2))
print(rdm2)

tf.Tensor(
[[ 0.13106444 -0.05365121]
 [ 0.22110713 -0.2858595 ]
 [-0.41451666  0.5252109 ]], shape=(3, 2), dtype=float32)


In [ ]:
# set_seed for reproduceability

random2 = tf.random.set_seed(6+2)
rdm2 = tf.random.normal(shape = (3,2))
rdm2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 1.2074401, -0.7452462],
       [ 0.6908678, -0.7635988],
       [-2.4725451,  0.583414 ]], dtype=float32)>

## **Shuffle the tensors**

In [ ]:
# Create the tensor
tensor1 = tf.constant([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])
tensor1

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]], dtype=int32)>

In [ ]:
# Shuffle the tensor
tf.random.shuffle(tensor1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [11, 12, 13],
       [ 4,  5,  6],
       [ 1,  2,  3]], dtype=int32)>

In [ ]:
# Shuffle tensor with the seed, seed gives the same shuffling
tf.random.shuffle(tensor1, seed = tf.random.set_seed(6))

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [ 1,  2,  3],
       [11, 12, 13],
       [ 4,  5,  6]], dtype=int32)>

## **Creating tensors with other ways and reshaping**

In [ ]:
tensor1 = tf.ones(shape=(5,5))
tensor1

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tensor2 = tf.zeros(shape = (7,7))
tensor2

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Creating tensors with numpy

import numpy as np
one = np.ones(shape = (1,25))
print(one.shape)

(1, 25)


In [ ]:
# Tensor conversion

tensor3 = tf.constant(one)
tensor3

<tf.Tensor: shape=(1, 25), dtype=float64, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1.]])>

In [ ]:
tensor4 = tf.constant(value = one, shape = (5,5))
tensor4

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])>

In [ ]:
print(f"Dimension = {tensor4.ndim}")
print(f"Shape = {tensor4.shape}")

Dimension = 2
Shape = (5, 5)


## **Getting informations from the tensor**
- Shape of the tensor - `shape`
- Dimension or Rank of the tensor - `ndim`
- Access values in the tensor - `axis`
- Returns total no. of values in the tensor - `size`

In [ ]:
# Create tensor
tensor1 = tf.zeros(shape=(2,5,3,6))
tensor1

<tf.Tensor: shape=(2, 5, 3, 6), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0.],
         [0., 0., 

In [ ]:
print("Data type = ", tensor1.dtype)
print("Shape of the tensor is = ", tensor1.shape)
print("Dimension of the tensor = ", tensor1.ndim)
print("Total no. of elements in the tensor = ", tf.size(tensor1))
print("Total no. of elements in the tensor = ", tf.size(tensor1).numpy())

print()
print("Shape of another axis = ", tensor1.shape[1])
print("Shape of another axis = ", tensor1[1].shape)
print("Shape of another axis = ", tensor1.shape[-1])

Data type =  <dtype: 'float32'>
Shape of the tensor is =  (2, 5, 3, 6)
Dimension of the tensor =  4
Total no. of elements in the tensor =  tf.Tensor(180, shape=(), dtype=int32)
Total no. of elements in the tensor =  180

Shape of another axis =  5
Shape of another axis =  (5, 3, 6)
Shape of another axis =  6


## **Indexing the values in the tensors - Adding new axis with `tf.newaxis` & `tf.expand_dims`**

In [ ]:
# Create the tensor
tensor1 = tf.random.normal(shape = (2,4,3,4), seed = tf.random.set_seed(4))
tensor1

<tf.Tensor: shape=(2, 4, 3, 4), dtype=float32, numpy=
array([[[[-0.07676513, -0.2082602 ,  1.9333363 ,  1.175166  ],
         [ 1.4444144 ,  1.3351023 ,  0.0987538 ,  0.47003892],
         [-0.89593434,  0.8269468 , -0.3298544 , -1.6903992 ]],

        [[ 2.1704402 , -1.0355538 ,  1.1871556 ,  0.44113445],
         [-0.7447429 ,  1.2710264 ,  0.7388742 ,  0.07137717],
         [-0.50871074,  0.15399624, -0.5843095 ,  0.24425206]],

        [[-0.89614534,  1.2474071 , -0.2823673 , -1.8227786 ],
         [ 0.08598502,  0.18523236,  1.0952697 ,  1.0587058 ],
         [-1.1825346 ,  0.696092  ,  0.8839624 ,  0.17423686]],

        [[-0.16251336, -0.7896537 ,  0.24229203, -0.52675635],
         [-0.3140981 , -0.24705702,  0.6397933 , -1.135537  ],
         [-1.1032122 ,  1.5286386 ,  0.76228625, -0.3429256 ]]],


       [[[-0.06027858, -1.0430243 , -0.1901275 ,  1.3248413 ],
         [-1.8228244 ,  1.5238873 ,  1.6719191 ,  0.2202732 ],
         [-1.4030557 , -0.10960167,  0.28856477, -0.91

In [ ]:
# Indexing

tensor1[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[-0.07676513, -0.2082602 ],
         [ 1.4444144 ,  1.3351023 ]],

        [[ 2.1704402 , -1.0355538 ],
         [-0.7447429 ,  1.2710264 ]]],


       [[[-0.06027858, -1.0430243 ],
         [-1.8228244 ,  1.5238873 ]],

        [[ 0.1307732 ,  0.06597125],
         [ 0.20673676,  0.09271695]]]], dtype=float32)>

In [ ]:
tensor1[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 4), dtype=float32, numpy=
array([[[[-0.07676513, -0.2082602 ,  1.9333363 ,  1.175166  ]]]],
      dtype=float32)>

In [ ]:
# Adding new asix

tensor2 = tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print("Shape = ",tensor2.shape)
print("Dimension = ",tensor2.ndim)


Shape =  (3, 3)
Dimension =  2


In [ ]:
tensor3 = tensor2[:, tf.newaxis, :]
tensor3

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>

In [ ]:
tensor3 = tensor2[:, tf.newaxis]
tensor3

<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>

In [ ]:
tensor4 = tensor2[tf.newaxis, :,:]
tensor4

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

In [ ]:
tensor5 = tensor2[...,tf.newaxis]
tensor5

<tf.Tensor: shape=(3, 3, 1), dtype=int32, numpy=
array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]], dtype=int32)>

In [ ]:
# Alternate for tf.newaxis
print("Axis = ", tensor2.shape)
tf.expand_dims(tensor2, 1)

Axis =  (3, 3)


<tf.Tensor: shape=(3, 1, 3), dtype=int32, numpy=
array([[[1, 2, 3]],

       [[4, 5, 6]],

       [[7, 8, 9]]], dtype=int32)>

## **Manipualting the tensors with basic operations**
- `+`, `-`, `*`, `/`
- Use tensorflow function to access the GPU

In [ ]:
# With normal operators

tensor1 = tf.constant([[45,30],[10,20]])
print((tensor1 + 10).numpy())

[[55 40]
 [20 30]]


In [ ]:
tensor1 - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[40, 25],
       [ 5, 15]], dtype=int32)>

In [ ]:
tensor1 * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[450, 300],
       [100, 200]], dtype=int32)>

In [ ]:
tensor1 / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[4.5, 3. ],
       [1. , 2. ]])>

In [ ]:
# With tensorflow functions

tf.multiply(tensor1, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[450, 300],
       [100, 200]], dtype=int32)>

In [ ]:
tf.add(tensor1, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[55, 40],
       [20, 30]], dtype=int32)>

In [ ]:
tf.subtract(tensor1, 10)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 20],
       [ 0, 10]], dtype=int32)>

In [ ]:
tf.divide(tensor1, 10)


<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[4.5, 3. ],
       [1. , 2. ]])>

## **[Matrix multiplication](http://matrixmultiplication.xyz/)**

### **Part-1**

In [ ]:
tensor1 = tf.constant([[3,6],[7,9]])
tf.matmul(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 51,  72],
       [ 84, 123]], dtype=int32)>

In [ ]:
# Normal multiplication
tensor1 * tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 9, 36],
       [49, 81]], dtype=int32)>

In [ ]:
# '@' used for matrix multiplication in python

tensor1 @ tensor1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 51,  72],
       [ 84, 123]], dtype=int32)>

In [ ]:
import numpy as np
np.array([[12,3,4],[33,2,1]]) @ np.array([[12,3,4],[33,2,1],[33,2,1]])

array([[375,  50,  55],
       [495, 105, 135]])

### **Part-2 (Reshaping) `tf.reshape()`, `tf.transpose()`**
- row x column
- Matrix_1 inner dimension(column) and Matrix_2 outer dimension(row) must match
- For eg: 2x3 and 3x2
- 3 and 3 are matching. Hence, we can multiply this.
- Result of this matrix be 2x2, the outer dimensions  of the input matrix.

In [ ]:
x = tf.constant([[1,2,3],[11,4,5]])
y = tf.constant([[1,2,9],[3,4,5]])
print(x)
print()
print(y)

tf.Tensor(
[[ 1  2  3]
 [11  4  5]], shape=(2, 3), dtype=int32)

tf.Tensor(
[[1 2 9]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [ ]:
Y = tf.reshape(y, shape = (3,2))
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [9, 3],
       [4, 5]], dtype=int32)>

In [ ]:
tf.matmul(x,Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[31, 23],
       [67, 59]], dtype=int32)>

In [ ]:
x, tf.reshape(x, shape = (3,2)), tf.transpose(x)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[ 1,  2,  3],
        [11,  4,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1,  2],
        [ 3, 11],
        [ 4,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 1, 11],
        [ 2,  4],
        [ 3,  5]], dtype=int32)>)

### **Part-3 Transpose and reshape**
- Matrix multlipications can be done by
    - `tf.matmul()`
    - `tf.tensordot()`
    - `@`

In [ ]:
x = tf.constant([[1,2,3],[4,5,6]])
y = tf.constant([[1,2,3],[4,5,6]])
x,y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

In [ ]:
x, tf.reshape(x, shape = (3,2)), tf.transpose(x)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 4],
        [2, 5],
        [3, 6]], dtype=int32)>)

In [ ]:
tf.matmul(x, tf.reshape(x, shape = (3,2)))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 28],
       [49, 64]], dtype=int32)>

In [ ]:
tf.matmul(x, tf.transpose(x))


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [ ]:
tf.tensordot(x,tf.transpose(x), axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

In [ ]:
x @ tf.transpose(x)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[14, 32],
       [32, 77]], dtype=int32)>

## **Type casting - to increase the speed during the training**

In [ ]:
x = tf.constant([[1,2,3]])
y = tf.constant([1.0,2.0])
x, y

(<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[1, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 2.], dtype=float32)>)

In [ ]:
tf.cast(x, dtype=tf.int16), tf.cast(y, tf.float16), tf.cast(y, tf.int16)

(<tf.Tensor: shape=(1, 3), dtype=int16, numpy=array([[1, 2, 3]], dtype=int16)>,
 <tf.Tensor: shape=(2,), dtype=float16, numpy=array([1., 2.], dtype=float16)>,
 <tf.Tensor: shape=(2,), dtype=int16, numpy=array([1, 2], dtype=int16)>)

## **Aggregating tensors**
- Finding minimum, maximum, mean, sum, variance and sandard deviations using TF.

In [ ]:
t = tf.constant(np.random.randint(0,100,80))
t

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([16, 96, 78, 62, 65, 38, 39,  1, 36, 60, 77, 58, 64, 23, 37, 52, 80,
       99, 22, 19, 65, 52, 34, 13, 10, 36, 62, 21,  7, 40, 64, 60, 37, 35,
       98, 61, 99, 54, 82, 32, 75, 55,  8, 53, 48, 76, 90, 54, 28, 96, 26,
       32, 87, 49, 25, 11,  6, 20, 96, 41, 58, 86, 54, 99, 15, 89, 55, 45,
       34,  5, 50, 24, 21, 62, 82,  4, 23, 29, 51, 48])>

In [ ]:
tf.reduce_min(t), tf.reduce_max(t), tf.reduce_sum(t), tf.reduce_mean(t)

(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=99>,
 <tf.Tensor: shape=(), dtype=int64, numpy=3894>,
 <tf.Tensor: shape=(), dtype=int64, numpy=48>)

In [ ]:
tf.math.reduce_variance(tf.cast(t, tf.float16)), tf.math.reduce_std(tf.cast(t, tf.float16))

(<tf.Tensor: shape=(), dtype=float16, numpy=741.0>,
 <tf.Tensor: shape=(), dtype=float16, numpy=27.22>)

In [ ]:
import tensorflow_probability as tfp

tfp.stats.variance(t)

<tf.Tensor: shape=(), dtype=int64, numpy=741>

In [ ]:
tfp.stats.stddev(tf.cast(t, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=27.22>

## **Finding positional maximum and minimum value in a tensor**

In [ ]:
t = tf.random.uniform(shape=[50],seed = tf.random.set_seed(42))
t

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.argmax(t)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
t[tf.argmax(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
assert t[tf.argmax(t)] == tf.reduce_max(t)

In [ ]:
t[tf.argmin(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [ ]:
tf.reduce_min(t)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## **Squeezing the dimensions**

In [ ]:
t = tf.constant(tf.random.uniform([50]), shape = (2,1,1,25))
t

<tf.Tensor: shape=(2, 1, 1, 25), dtype=float32, numpy=
array([[[[0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ,
          0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384,
          0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178,
          0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018,
          0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877]]],


       [[[0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155,
          0.20418596, 0.28848922, 0.65142167, 0.7106751 , 0.8695041 ,
          0.23745108, 0.6688912 , 0.7115667 , 0.21899498, 0.7702793 ,
          0.45055628, 0.95493364, 0.71695936, 0.98945487, 0.1511141 ,
          0.06240606, 0.15209746, 0.99522185, 0.7830266 , 0.10455871]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(t)

<tf.Tensor: shape=(2, 25), dtype=float32, numpy=
array([[0.803156  , 0.49777734, 0.37054038, 0.9118674 , 0.637642  ,
        0.18209696, 0.63791955, 0.27701473, 0.04227114, 0.84219384,
        0.90637195, 0.222556  , 0.9198462 , 0.68789077, 0.42705178,
        0.878158  , 0.6943959 , 0.46567595, 0.52925766, 0.33019018,
        0.12754858, 0.16153514, 0.5085137 , 0.44301772, 0.35205877],
       [0.8969147 , 0.24940813, 0.76328313, 0.85935795, 0.08480155,
        0.20418596, 0.28848922, 0.65142167, 0.7106751 , 0.8695041 ,
        0.23745108, 0.6688912 , 0.7115667 , 0.21899498, 0.7702793 ,
        0.45055628, 0.95493364, 0.71695936, 0.98945487, 0.1511141 ,
        0.06240606, 0.15209746, 0.99522185, 0.7830266 , 0.10455871]],
      dtype=float32)>

## **One-hot encoding**

In [ ]:
a = [1,2,3]
tf.one_hot(a, depth=4)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(a, depth=4, on_value="ON", off_value="off")

<tf.Tensor: shape=(3, 4), dtype=string, numpy=
array([[b'off', b'ON', b'off', b'off'],
       [b'off', b'off', b'ON', b'off'],
       [b'off', b'off', b'off', b'ON']], dtype=object)>

## **Other math operations**
- Square, Square root and log

In [ ]:
t = tf.range(10)
t

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(t)

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(t, tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([0.   , 1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828,
       3.   ], dtype=float16)>

In [ ]:
tf.math.log(tf.cast(t, tf.float16))

<tf.Tensor: shape=(10,), dtype=float16, numpy=
array([  -inf, 0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 ,
       2.08  , 2.197 ], dtype=float16)>

## **Tensors and NumPy**

In [ ]:
# Creating tensors by numpy array and python list

a = tf.constant(np.array([1.0,2.0,3.0]))
b = tf.constant([1.0,2.0,3.0])
a, a.dtype, b, b.dtype

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>,
 tf.float64,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 tf.float32)

In [ ]:
# Converting tensors to numpy

a.numpy(), type(a.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [ ]:
np.array(a), type(np.array(a))

(array([1., 2., 3.]), numpy.ndarray)